//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtwCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtwCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clear screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearScreen_HelpText {
            get {
                return ResourceManager.GetString("ClearScreen_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear all active session. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearSession_HelpText {
            get {
                return ResourceManager.GetString("ClearSession_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start to collect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Collect_HelpText {
            get {
                return ResourceManager.GetString("Collect_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Log Level (Trace = 0, Debug = 1, Information = 2, Warning = 3, Error = 4, Critical = 5, None = 6) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Collect_Level_HelpText {
            get {
                return ResourceManager.GetString("Collect_Level_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration name to display. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_ConfigurationName_HelpText {
            get {
                return ResourceManager.GetString("Configuration_ConfigurationName_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} error(s) occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press Esc key to stop. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PressEscKeyToStop {
            get {
                return ResourceManager.GetString("PressEscKeyToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show verbose output. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VerbBase_Verbose {
            get {
                return ResourceManager.GetString("VerbBase_Verbose", resourceCulture);
            }
        }
    }
}
